# Uncomment this line to define a global platform for your project
# platform :ios, ’9.0’
use_frameworks!
pod 'Firebase/Database'
pod 'Firebase/Core’
pod 'Firebase/Auth'
pod 'AFNetworking', '~> 3.0'
pod 'JBParallaxCell'

target 'PREZZO' do
end

target 'PREZZOTests' do
end

target 'PREZZOUITests' do
end

